name: Raffle Scraper

on:
  schedule:
    # Every hour at minute 55
    - cron: '55 * * * *'

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Python script
        run: python Winter_Scraper.py