name: Raffle Scraper

on:
  schedule:
    # Every hour at minute 55
    - cron: '55 * * * *'

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -q selenium
      - name: Run Python script
        run: python Winter_Scraper.py
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add raffles
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Weekly update from GitHub Actions"
            git push origin ${{ github.ref_name }}
          fi